name: Lint & Test - Frontend

on:
  push:
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn eslint --ignore-path .gitignore .

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Run the TypeScript compiler
        run: yarn tsc
